from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one replacement, found {count}")
    p.write_text(text.replace(old, new, 1))


# Replace per-task mutex/CV/shared_ptr state with one CoreWorker-level table and
# group waiter lists. TaskSpecification remains owned by the table until all
# prerequisite frontier groups are durable.
replace_once(
    "src/ray/core_worker/core_worker.h",
    '''  struct DeferredRecoveryTaskState {\n    std::mutex mutex;\n    std::condition_variable cv;\n    bool ready = false;\n  };\n\n  // Locally returned task refs can precede upstream Frontier durability, but\n  // chained activation must never cross that boundary.\n  mutable std::mutex recovery_frontier_deferred_task_mutex_;\n  mutable absl::flat_hash_map<TaskID, std::shared_ptr<DeferredRecoveryTaskState>>\n      recovery_frontier_deferred_tasks_;\n''',
    '''  struct DeferredRecoveryTaskState {\n    size_t remaining_groups = 0;\n    std::optional<TaskSpecification> task_to_dispatch;\n  };\n\n  // Locally returned task refs can precede upstream Frontier durability, but\n  // chained activation must never cross that boundary. One CoreWorker-level\n  // lock/CV replaces a mutex/CV allocation per task, and one waiter vector per\n  // frontier group releases all downstream tasks sharing that durability gate.\n  mutable std::mutex recovery_frontier_deferred_task_mutex_;\n  mutable std::condition_variable recovery_frontier_deferred_task_cv_;\n  mutable absl::flat_hash_map<TaskID, DeferredRecoveryTaskState>\n      recovery_frontier_deferred_tasks_;\n  mutable absl::flat_hash_map<TaskID, std::vector<TaskID>>\n      recovery_frontier_deferred_group_waiters_;\n''')

replace_once(
    "src/ray/core_worker/core_worker.h",
    '''  void WaitForDeferredRecoveryTaskDependencies(const TaskID &task_id) const;\n\n  using RecoveryWitnessPublishCallback =\n''',
    '''  void WaitForDeferredRecoveryTaskDependencies(const TaskID &task_id) const;\n\n  /// Complete one group durability gate, decrementing all tasks waiting on it\n  /// and dispatching every task whose final prerequisite just became durable.\n  void CompleteDeferredRecoveryFrontierGroup(const TaskID &group_id) const;\n\n  using RecoveryWitnessPublishCallback =\n''')

# Replace the per-task condition variable wait with a predicate on the shared
# deferred-task table, and add group-level completion/dispatch batching.
replace_once(
    "src/ray/core_worker/core_worker.cc",
    '''void CoreWorker::WaitForDeferredRecoveryTaskDependencies(\n    const TaskID &task_id) const {\n  std::shared_ptr<DeferredRecoveryTaskState> state;\n  {\n    std::lock_guard<std::mutex> lock(recovery_frontier_deferred_task_mutex_);\n    const auto it = recovery_frontier_deferred_tasks_.find(task_id);\n    if (it == recovery_frontier_deferred_tasks_.end()) {\n      return;\n    }\n    state = it->second;\n  }\n\n  std::unique_lock<std::mutex> lock(state->mutex);\n  state->cv.wait(lock, [&state] { return state->ready; });\n}\n''',
    '''void CoreWorker::WaitForDeferredRecoveryTaskDependencies(\n    const TaskID &task_id) const {\n  std::unique_lock<std::mutex> lock(recovery_frontier_deferred_task_mutex_);\n  recovery_frontier_deferred_task_cv_.wait(lock, [this, &task_id] {\n    return recovery_frontier_deferred_tasks_.find(task_id) ==\n           recovery_frontier_deferred_tasks_.end();\n  });\n}\n\nvoid CoreWorker::CompleteDeferredRecoveryFrontierGroup(\n    const TaskID &group_id) const {\n  // One allocation per completed group, rather than one readiness object,\n  // atomic counter, and TaskSpecification shared_ptr per downstream task.\n  auto ready_tasks = std::make_shared<std::vector<TaskSpecification>>();\n\n  {\n    std::lock_guard<std::mutex> lock(recovery_frontier_deferred_task_mutex_);\n    const auto group_it =\n        recovery_frontier_deferred_group_waiters_.find(group_id);\n    if (group_it == recovery_frontier_deferred_group_waiters_.end()) {\n      return;\n    }\n\n    ready_tasks->reserve(group_it->second.size());\n    for (const TaskID &task_id : group_it->second) {\n      auto task_it = recovery_frontier_deferred_tasks_.find(task_id);\n      RAY_CHECK(task_it != recovery_frontier_deferred_tasks_.end())\n          << "Missing deferred Recovery Frontier task state for " << task_id\n          << " while completing group " << group_id;\n      RAY_CHECK_GT(task_it->second.remaining_groups, 0u);\n\n      --task_it->second.remaining_groups;\n      if (task_it->second.remaining_groups != 0) {\n        continue;\n      }\n\n      RAY_CHECK(task_it->second.task_to_dispatch.has_value());\n      ready_tasks->push_back(\n          std::move(*task_it->second.task_to_dispatch));\n      recovery_frontier_deferred_tasks_.erase(task_it);\n    }\n\n    recovery_frontier_deferred_group_waiters_.erase(group_it);\n  }\n\n  // Erasing a task from the shared table is the readiness transition observed\n  // by chained submissions. Wake them before posting the now-safe dispatches.\n  recovery_frontier_deferred_task_cv_.notify_all();\n\n  if (ready_tasks->empty()) {\n    return;\n  }\n\n  io_service_.post(\n      [this, ready_tasks]() mutable {\n        for (TaskSpecification &task : *ready_tasks) {\n          normal_task_submitter_->SubmitTask(std::move(task));\n        }\n      },\n      "CoreWorker.SubmitTasksAfterRecoveryFrontierCommit");\n}\n''')

# Replace per-task heap state/atomics/callbacks with shared task table + one
# publication callback per frontier group.
replace_once(
    "src/ray/core_worker/core_worker.cc",
    '''  if (defer_recovery_frontier_dispatch &&\n      !deferred_recovery_frontier_groups.empty()) {\n    const TaskID deferred_task_id = task_spec.TaskId();\n    auto readiness = std::make_shared<DeferredRecoveryTaskState>();\n    {\n      std::lock_guard<std::mutex> lock(recovery_frontier_deferred_task_mutex_);\n      const auto inserted = recovery_frontier_deferred_tasks_.emplace(\n          deferred_task_id, readiness);\n      RAY_CHECK(inserted.second)\n          << "Duplicate deferred Recovery Frontier task state for "\n          << deferred_task_id;\n    }\n\n    auto remaining = std::make_shared<std::atomic<size_t>>(\n        deferred_recovery_frontier_groups.size());\n    auto task_to_dispatch =\n        std::make_shared<TaskSpecification>(std::move(task_spec));\n\n    for (const DeferredRecoveryFrontierGroup &group :\n         deferred_recovery_frontier_groups) {\n      PublishRecoveryFrontierGroupAsync(\n          group.group_id,\n          group.protection_manifest,\n          [this, deferred_task_id, readiness, remaining, task_to_dispatch]() mutable {\n            if (remaining->fetch_sub(1) != 1) {\n              return;\n            }\n\n            {\n              std::lock_guard<std::mutex> ready_lock(readiness->mutex);\n              readiness->ready = true;\n            }\n            readiness->cv.notify_all();\n\n            {\n              std::lock_guard<std::mutex> map_lock(\n                  recovery_frontier_deferred_task_mutex_);\n              const auto it =\n                  recovery_frontier_deferred_tasks_.find(deferred_task_id);\n              if (it != recovery_frontier_deferred_tasks_.end() &&\n                  it->second == readiness) {\n                recovery_frontier_deferred_tasks_.erase(it);\n              }\n            }\n\n            io_service_.post(\n                [this, task_to_dispatch]() mutable {\n                  normal_task_submitter_->SubmitTask(\n                      std::move(*task_to_dispatch));\n                },\n                "CoreWorker.SubmitTaskAfterRecoveryFrontierCommit");\n          });\n    }\n  } else {\n''',
    '''  if (defer_recovery_frontier_dispatch &&\n      !deferred_recovery_frontier_groups.empty()) {\n    const TaskID deferred_task_id = task_spec.TaskId();\n    std::vector<DeferredRecoveryFrontierGroup> groups_to_start;\n\n    {\n      std::lock_guard<std::mutex> lock(recovery_frontier_deferred_task_mutex_);\n      auto [task_it, task_inserted] =\n          recovery_frontier_deferred_tasks_.try_emplace(deferred_task_id);\n      RAY_CHECK(task_inserted)\n          << "Duplicate deferred Recovery Frontier task state for "\n          << deferred_task_id;\n\n      task_it->second.remaining_groups =\n          deferred_recovery_frontier_groups.size();\n      task_it->second.task_to_dispatch.emplace(std::move(task_spec));\n\n      groups_to_start.reserve(deferred_recovery_frontier_groups.size());\n      for (const DeferredRecoveryFrontierGroup &group :\n           deferred_recovery_frontier_groups) {\n        auto [group_it, group_inserted] =\n            recovery_frontier_deferred_group_waiters_.try_emplace(\n                group.group_id);\n        group_it->second.push_back(deferred_task_id);\n\n        // Only the first waiter starts the group's asynchronous publication.\n        // Later tasks merely join the waiter vector and add no callbacks,\n        // timers, atomics, or per-task readiness objects.\n        if (group_inserted) {\n          groups_to_start.push_back(group);\n        }\n      }\n    }\n\n    for (const DeferredRecoveryFrontierGroup &group : groups_to_start) {\n      PublishRecoveryFrontierGroupAsync(\n          group.group_id,\n          group.protection_manifest,\n          [this, group_id = group.group_id]() {\n            CompleteDeferredRecoveryFrontierGroup(group_id);\n          });\n    }\n  } else {\n''')

print("Recovery Frontier group-level deferred dispatch patch applied")
