#!/usr/bin/env python3
from pathlib import Path

p = Path("tools/_profile_k1_witness_rpc_phases.py")
text = p.read_text()
old = '''# Both witness callback sites use the same breakdown argument sequence.\ncore = Path("src/ray/core_worker/core_worker.cc")\ntext = core.read_text()\nold = \'\'\'manager->RecordWitnessUpdateRpcBreakdown(\\n            reply.client_queue_time_ns(),\\n            reply.witness_batch_queue_time_ns(),\\n            reply.witness_handler_time_ns(),\\n            reply.witness_mutex_wait_time_ns(),\\n            reply.witness_mutex_hold_time_ns(),\\n            reply.client_batch_leader(),\\n            reply.client_batch_size());\'\'\'\nnew = \'\'\'manager->RecordWitnessUpdateRpcBreakdown(\\n            reply.client_queue_time_ns(),\\n            reply.client_submit_to_cq_time_ns(),\\n            reply.client_cq_to_main_loop_time_ns(),\\n            reply.client_main_loop_to_batch_callback_time_ns(),\\n            reply.witness_batch_queue_time_ns(),\\n            reply.witness_handler_time_ns(),\\n            reply.witness_mutex_wait_time_ns(),\\n            reply.witness_mutex_hold_time_ns(),\\n            reply.client_batch_leader(),\\n            reply.client_batch_size());\'\'\'\ncount = text.count(old)\nif count != 2:\n    raise RuntimeError(f"core_worker.cc: expected 2 witness breakdown sites, found {count}")\ntext = text.replace(old, new)\ncore.write_text(text)\n'''
new = '''# The two witness callback sites use the same arguments but different indentation.\nimport re\ncore = Path("src/ray/core_worker/core_worker.cc")\ntext = core.read_text()\npattern = re.compile(\n    r"manager->RecordWitnessUpdateRpcBreakdown\\(\\s*"\n    r"reply\\.client_queue_time_ns\\(\\),\\s*"\n    r"reply\\.witness_batch_queue_time_ns\\(\\),\\s*"\n    r"reply\\.witness_handler_time_ns\\(\\),\\s*"\n    r"reply\\.witness_mutex_wait_time_ns\\(\\),\\s*"\n    r"reply\\.witness_mutex_hold_time_ns\\(\\),\\s*"\n    r"reply\\.client_batch_leader\\(\\),\\s*"\n    r"reply\\.client_batch_size\\(\\)\\);"\n)\nreplacement = """manager->RecordWitnessUpdateRpcBreakdown(\n            reply.client_queue_time_ns(),\n            reply.client_submit_to_cq_time_ns(),\n            reply.client_cq_to_main_loop_time_ns(),\n            reply.client_main_loop_to_batch_callback_time_ns(),\n            reply.witness_batch_queue_time_ns(),\n            reply.witness_handler_time_ns(),\n            reply.witness_mutex_wait_time_ns(),\n            reply.witness_mutex_hold_time_ns(),\n            reply.client_batch_leader(),\n            reply.client_batch_size());"""\ntext, count = pattern.subn(replacement, text)\nif count != 2:\n    raise RuntimeError(f"core_worker.cc: expected 2 witness breakdown sites, found {count}")\ncore.write_text(text)\n'''
if text.count(old) != 1:
    raise RuntimeError(f"expected one old applicator block, found {text.count(old)}")
p.write_text(text.replace(old, new, 1))
print("Fixed K1 phase applicator indentation matching.")
